Header and Footer
NUS-Fintech-Society/SD_Careers_Platform_AY24-25 pull request #1
Opened 2024-10-17 15:57 UTC by howen02

Created header and footer components adding them to the layout file. Installed headlessui and heroicons for tailwind components.

2024-10-25 07:21 UTC, nathanshew requested changes

2024-10-25 07:21 UTC, nathanshew commented on src/app/components/Navbar.tsx
Good work! Is it possible to use Roboto?

2024-10-25 07:21 UTC, nathanshew commented on src/app/components/Footer.tsx
Good work! Is it possible to use Montserrat? Can we also have a little padding beside the Let's Connect words? Thank you!

Understand the use of our existing 4 icons and a dark blue placeholder before the picture is obtained!

2024-10-25 07:54 UTC, nathanshew commented on src/app/components/Footer.tsx
https://s3-alpha-sig.figma.com/img/06a0/72ce/54741d080e2936d1db20e54273e0b1c0?Expires=1730678400&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=DGyUZnUX64l6D0A-djT2o-g8BVB72-vvl5reScrdbwD-rRQKVHpj16S-I-F7jyljYL6gNzMVJIU~HRPz4XO8leiJ4ShbHG4m~Gs0MlmABYZrxYQZsxX1~r3~ot9PjmleafBMJBodvopDxTtyf6ESNDlqKi9cCvjxbW1g31q5S5YiCXKiJfxoIKQ~YBecIUkrG9altjCJY6C40FWV-EDFRYx18dHJlD6gObSj4GPwvx3UOI4UtUcxM13KF2o6LGvn5ehgHEy8aQA2ZLtyG6tByUidZ86KBV5xSpDxlbv2IJxxOPThx6RhaCSuN8Gz~uja-rrPq5NmEJmhNQO7m9RUFg__

I believe this is the photo they used!

2024-10-29 11:42 UTC, nathanshew commented on src/app/components/Navbar.tsx
Can look at Beam's commit

2024-12-11 07:03 UTC, howen02 commented
@nathanshew made changes as requested

2025-01-01 14:18 UTC, merged

2025-01-01 14:18 UTC, nathanshew commented
LGTM, Thank you!